spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc.lob.non_contextual_creation: true
    open-in-view: false

management:
  endpoint:
    health:
      db.enabled: true
      defaults.enabled: false
      gitHub.enabled: true

app:
  jenkins:
    update-center: https://updates.jenkins.io/current/update-center.actual.json
    documentation-urls: https://updates.jenkins.io/current/plugin-documentation-urls.json
  github:
    app-id: 728867
    private-key-path: /usr/local/plugin-health-scoring/key.pem
    app-installation-name: sridamul
  cron:
    update-center: 0 */2 * * * *
    probe-engine: 0 */2 * * * *

---

spring.config.activate.on-profile: dev
logging.level:
  io.jenkins.pluginhealth: DEBUG

management:
  endpoint:
    health:
      show-components: always
      show-details: always
